# Generated by Django 5.2.5 on 2025-08-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('krasovka', 'Krasovka'), ('shim', 'Shim'), ('kiyim', 'Kiyim'), ('kurtka', 'Kurtka')], max_length=50),
        ),
    ]
