# Generated by Django 5.2.4 on 2025-08-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
