services:
  - type: web
    name: myapp
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    disk:
      name: media
      mountPath: /opt/render/project/src/media
