# Generated by Django 5.2.5 on 2025-08-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('product', models.CharField(max_length=200, verbose_name='Buyurtma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
            ],
        ),
    ]
