# Generated by Django 5.2.5 on 2025-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Kiym modeli:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi:')),
                ('img', models.ImageField(upload_to='home/', verbose_name='Rasm:')),
            ],
        ),
    ]
