# Generated by Django 5.2.5 on 2025-08-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headnav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bosh sahifa ismi:')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='azgina malumot:')),
            ],
        ),
        migrations.RemoveField(
            model_name='box',
            name='title',
        ),
    ]
